paper: switch template, refactor sections, add pretty code
Signed-off-by: Michael Sevilla <mikesevilla3@gmail.com>

diff --git a/paper/build b/paper/build
--- a/paper/build
+++ b/paper/build
@@ -1,5 +1,7 @@
 #!/bin/bash
-set -x
+
+rm -r _minted-paper paper.aux paper.bbl paper.blg paper.log paper.out paper.synctex.gz
+set -ex
 
 # Build the paper
 docker rm -f latex || true
@@ -7,16 +9,19 @@ docker run \
   --name latex \
   --entrypoint=/bin/bash \
   -v `pwd`/:/mnt \
-  ivotron/texlive:latest -c \
-    "cd /mnt ; pdflatex paper && bibtex paper && pdflatex paper && pdflatex paper" &> build.log
+  ivotron/texlive_v2:latest -c \
+    "cd /mnt ; \
+     pdflatex -synctex=1 -interaction=nonstopmode -shell-escape paper && \
+     bibtex paper && \
+     pdflatex -synctex=1 -interaction=nonstopmode -shell-escape paper && \
+     pdflatex -synctex=1 -interaction=nonstopmode -shell-escape paper" &> build.log
 
-if [ $? != "0" ] ; then
-  echo "ERROR"
+ERR=$?
+if [ $ERR != "0" ] ; then
+  echo "ERROR: $ERR"
   cat build.log
   exit 1
 fi
 
 echo "SUCCESS"
-#open paper.pdf
-
 exit 0
